config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :posts

  get 'index', to: 'homes#index'
  get 'about', to: 'homes#about'

  # Login
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy', as: :logout

  get 'signup', to: 'users#new', as: :signup
  post 'signup', to: 'users#create'

  #PHYSIOLOGY
  get 'producto_extras', to: 'extras#indexProducts'
  get 'producto_extras/:id', to: 'extras#showProduct'

  #PHYSIOLOGY
  get 'producto_physiologies', to: 'physiologies#indexProducts'
  get 'producto_physiologies/:id', to: 'physiologies#showProduct'

  get 'producto_physiology_finals', to: 'physiology_finals#indexProducts'
  get 'producto_physiology_finals/:id', to: 'physiology_finals#showProduct'

  #ANATOMY A
  get 'producto_anatomy_as', to: 'anatomy_as#indexProducts'
  get 'producto_anatomy_as/:id', to: 'anatomy_as#showProduct'

  get 'producto_anatomy_a_finals', to: 'anatomy_a_finals#indexProducts'
  get 'producto_anatomy_a_finals/:id', to: 'anatomy_a_finals#showProduct'

  #ANATOMY B
  get 'producto_anatomy_bs', to: 'anatomy_bs#indexProducts'
  get 'producto_anatomy_bs/:id', to: 'anatomy_bs#showProduct'

  get 'producto_anatomy_b_finals', to: 'anatomy_b_finals#indexProducts'
  get 'producto_anatomy_b_finals/:id', to: 'anatomy_b_finals#showProduct'

  #ANATOMY C
  get 'producto_anatomy_cs', to: 'anatomy_cs#indexProducts'
  get 'producto_anatomy_cs/:id', to: 'anatomy_cs#showProduct'

  get 'producto_anatomy_c_finals', to: 'anatomy_c_finals#indexProducts'
  get 'producto_anatomy_c_finals/:id', to: 'anatomy_c_finals#showProduct'

  #HISTOLOGY
  get 'producto_histologies', to: 'histologies#indexProducts'
  get 'producto_histologies/:id', to: 'histologies#showProduct'

  get 'producto_histology_finals', to: 'histology_finals#indexProducts'
  get 'producto_histology_finals/:id', to: 'histology_finals#showProduct'

  #BIOLOGY
  get 'producto_biologies', to: 'biologies#indexProducts'
  get 'producto_biologies/:id', to: 'biologies#showProduct'

  get 'producto_biology_finals', to: 'biology_finals#indexProducts'
  get 'producto_biology_finals/:id', to: 'biology_finals#showProduct'

  #BIOCHEMISTRY
  get 'producto_biochemistries', to: 'biochemistries#indexProducts'
  get 'producto_biochemistries/:id', to: 'biochemistries#showProduct'

  get 'producto_biochemistry_finals', to: 'biochemistry_finals#indexProducts'
  get 'producto_biochemistry_finals/:id', to: 'biochemistry_finals#showProduct'

  scope :admin do
    resources :users do
      collection do
        get 'generate_random_string'
      end
    end

    resources :extras do
      resources :extra_contents
    end

    resources :physiologies do
      resources :physiology_contents
    end
    resources :anatomy_as do
      resources :anatomy_a_contents
    end
    resources :anatomy_bs do
      resources :anatomy_b_contents
    end
    resources :anatomy_cs do
      resources :anatomy_c_contents
    end
    resources :histologies do
      resources :histology_contents
    end
    resources :biologies do
      resources :biology_contents
    end
    resources :biochemistries do
      resources :biochemistry_contents
    end

    resources :anatomy_a_finals do
      resources :anatomy_a_final_contents
    end

    resources :anatomy_b_finals do
      resources :anatomy_b_final_contents
    end

    resources :anatomy_c_finals do
      resources :anatomy_c_final_contents
    end

    resources :histology_finals do
      resources :histology_final_contents
    end

    resources :biology_finals do
      resources :biology_final_contents
    end

    resources :biochemistry_finals do
      resources :biochemistry_final_contents
    end

    resources :physiology_finals do
      resources :physiology_final_contents
    end
    # resources :finals, path: 'final' do
    #   resources :final_contents
    # end
  end
end

app/models/physiology_final.rb
class PhysiologyFinal < ApplicationRecord
  has_many :physioloy_final_contents, dependent: :destroy

  validates :title, presence: true
end

app/controllers/physiology_finals_controller.rb
class PhysiologyFinalsController < ApplicationController
  def index
    authorize PhysiologyFinal
    @physiology_finals = PhysiologyFinal.all
    #@pagy, @physiology_finals = pagy(PhysiologyFinal.all)
  end

  def indexProducts
    authorize PhysiologyFinal
    @physiology_finals = PhysiologyFinal.all
  end

  def show
    authorize PhysiologyFinal
    @physiology_final = PhysiologyFinal.find(params[:id])
  end

  def showProduct
    authorize PhysiologyFinal
    @physiology_final = PhysiologyFinal.find(params[:id])
  end

  def new
    authorize PhysiologyFinal
    @physiology_final = PhysiologyFinal.new
  end

  def create
    authorize PhysiologyFinal
    @physiology_final = PhysiologyFinal.new(physiology_final_params)

    if @physiology_final.save
      redirect_to @physiology_final
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize PhysiologyFinal
    @physiology_final = PhysiologyFinal.find(params[:id])
  end

  def update
    authorize PhysiologyFinal
    @physiology_final = PhysiologyFinal.find(params[:id])

    if @physiology_final.update(physiology_final_params)
      redirect_to @physiology_final
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize PhysiologyFinal
    @physiology_final = PhysiologyFinal.find(params[:id])
    @physiology_final.destroy

    redirect_to physiology_finals_path, status: :see_other
  end

  private

  def physiology_final_params
    params.require(:physiology_final).permit(:title, :description, :text)
  end
end

app/views/physiology_finals/_form.html.erb
<div id="admin_form">
  <%= form_with model: @physiology_final do |f| %>
    
    <div class="form-group div_card">
      <%= f.label 'Titulo' %><br>
      <%= f.text_field :title, class:"form-control" %>
      <% @physiology_final.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    
    <div class="form-group div_card">
      <%= f.label 'Link del archivo' %><br>
      <%= f.text_field :text, class:"form-control" %>
      <% @physiology_final.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group div_card">
      <%= f.label 'Descripción' %><br>
      <%= f.text_area :description, class:"form-control" %><br>
      <% @physiology_final.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class="div_card">
      <%= f.submit class:"btn btn-primary" %>
    </div>
  <% end %>

</div>
<br>

app/views/physiology_finals/edit.html.erb
<div id="admin_form">
    <br>
    <h1 class="title_admin"> Editar tema </h1>
    
    <%= render "form", physiology_final: @physiology_final %>

</div>

app/views/physiology_finals/index.html.erb
<div id="admin_container_physiology_finals">
  <h1 class="title_admin" style="text-align: center; padding: 215px 15px 0px;">Cursada de Fisiología</h1>
  <div class="link_new_theme">
    <p class="link_new_theme"><%= link_to "Nuevo Tema", new_physiology_final_path, class: "btn btn-warning mb-2" %></p>
  </div>
  <div class="table-responsive">
    <table id="physiology_final_table" class="table table-bordered table-hover">
      <thead>
        <tr>
          <th class="pink-background">Título</th>
          <th class="pink-background">Descripción</th>
          <th class="pink-background">Editar</th>
          <th class="pink-background">Eliminar</th>
        </tr>
      </thead>
      <tbody>
        <% @physiology_finals.each do |physiology_final| %>
          <tr>
            <td><%= link_to physiology_final.title, physiology_final_path(physiology_final) %></td>
            <td><%= physiology_final.description %></td>
            <td><%= link_to "Editar", edit_physiology_final_path(physiology_final), class: "btn btn-success" %></td>
            <td><%= link_to "Eliminar", physiology_final_path(physiology_final), data: { turbo_method: :delete, turbo_confirm: "¿Estás seguro?" }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
</div>

app/views/physiology_finals/indexProducts.html.erb
<div id="admin_container">
    <br>
    <h1 class="title_admin" style="text-align: center; padding: 215px 15px 0px;;">Final de Fisiología</h1>
    <br>
        <% @physiology_finals.each do |physiology_final| %>
            <div class="card text-center admin_card"  style="background-color: #E2CAAE; margin: 10px;">
                <div class="card-body">
                    <h5 class="card-title"><%= link_to physiology_final.title, producto_physiology_finals_content_path(physiology_final) %></h5>
                    <p class="card-text"><%= raw physiology_final.text %></p>
                    <p class="card-text"><%= physiology_final.description %></p>
                </div>
            </div>
            <br>
        <% end %>

</div>
<br>

app/views/physiology_finals/new.html.erb
<div id="admin_form">
    
    <h1 class="title_admin"> Nuevo tema </h1>
    
    <%= render "form", physiology_final: @physiology_final %>

</div>

app/views/physiology_finals/show.html.erb
<div id="admin_container">
  <h2 id="admin_form" class="subtitle">Contenido del Final de Fisiología</h2>
  <br>
  <div class="link_new_theme" style="text-align: center;">
    <p class="link_new_theme"><%= link_to "Cursadas", physiology_finals_path, class: "btn btn-warning mb-2" %></p>
  </div>  
  <br>
  <div class="card text-center admin_card">
    <div class="card-body">
      <h5 class="card-title"><%= @physiology_final.title %></h5>
      <p class="card-text"><%= raw @physiology_final.text %></p>
      <p class="card-text"><%= raw @physiology_final.description %></p>

      
      <%= link_to "Editar", edit_physiology_final_path(@physiology_final), class:"btn btn-success" %>
      <%= link_to "Eliminar", physiology_final_path(@physiology_final), data: {
        turbo_method: :delete,
        turbo_confirm: "Estas seguro?"
      }, class:"btn btn-danger" %>
    </div>
  </div>
    
  
  <%= render @physiology_final.physiology_final_contents %>
  
  <h2 id="admin_form" class="subtitle">Agregar Contenido</h2>
  <%= render 'physiology_final_contents/form' %>

</div>

app/views/physiology_finals/showProduct.html.erb
<div id="physiology_final_container">
  <br>
  <h1 class="title_admin" style="text-align: center; margin: 215px 15px 0px;">Contenido del Final de Fisiología</h1>
  <br>
  <div class="card text-center cursada_card">
    <div class="card-body">
      <h5 class="card-title"><%= @physiology_final.title %></h5>
      <p class="card-text"><%= raw @physiology_final.text %></p>
      <p class="card-text"><%= raw @physiology_final.description %></p>
    </div>
  </div>
    
  
  <h2  class="physiology_final_subtitle"style="text-align: center; margin: 5px; padding: 5px;">Contenido</h2>
  <div class="div_card_container">
    <br />
    <% @physiology_final.physiology_final_contents.each do |physiology_final_contents| %>
      <div class="card text-center div_card_children">
        <div class="card-body">
          <strong>
            <h5 class="card-title"><%= physiology_final_contents.title %></h5>
          </strong>
          <h5 class="card-title"><%= raw physiology_final_contents.text %></h5>
          <p class="card-text"><%= raw physiology_final_contents.description %></p>
        </div>
      </div>
    <% end %>
    <br />
  </div>
</div>