config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :posts

  get 'index', to: 'homes#index'
  get 'about', to: 'homes#about'

  # Login
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy', as: :logout

  get 'signup', to: 'users#new', as: :signup
  post 'signup', to: 'users#create'

  #PHYSIOLOGY
  get 'producto_extras', to: 'extras#indexProducts'
  get 'producto_extras/:id', to: 'extras#showProduct'

  #PHYSIOLOGY
  get 'producto_physiologies', to: 'physiologies#indexProducts'
  get 'producto_physiologies/:id', to: 'physiologies#showProduct'

  get 'producto_physiology_finals', to: 'physiology_finals#indexProducts'
  get 'producto_physiology_finals/:id', to: 'physiology_finals#showProduct'

  #ANATOMY A
  get 'producto_anatomy_as', to: 'anatomy_as#indexProducts'
  get 'producto_anatomy_as/:id', to: 'anatomy_as#showProduct'

  get 'producto_anatomy_a_finals', to: 'anatomy_a_finals#indexProducts'
  get 'producto_anatomy_a_finals/:id', to: 'anatomy_a_finals#showProduct'

  #ANATOMY B
  get 'producto_anatomy_bs', to: 'anatomy_bs#indexProducts'
  get 'producto_anatomy_bs/:id', to: 'anatomy_bs#showProduct'

  get 'producto_anatomy_b_finals', to: 'anatomy_b_finals#indexProducts'
  get 'producto_anatomy_b_finals/:id', to: 'anatomy_b_finals#showProduct'

  #ANATOMY C
  get 'producto_anatomy_cs', to: 'anatomy_cs#indexProducts'
  get 'producto_anatomy_cs/:id', to: 'anatomy_cs#showProduct'

  get 'producto_anatomy_c_finals', to: 'anatomy_c_finals#indexProducts'
  get 'producto_anatomy_c_finals/:id', to: 'anatomy_c_finals#showProduct'

  #HISTOLOGY
  get 'producto_histologies', to: 'histologies#indexProducts'
  get 'producto_histologies/:id', to: 'histologies#showProduct'

  get 'producto_histology_finals', to: 'histology_finals#indexProducts'
  get 'producto_histology_finals/:id', to: 'histology_finals#showProduct'

  #BIOLOGY
  get 'producto_biologies', to: 'biologies#indexProducts'
  get 'producto_biologies/:id', to: 'biologies#showProduct'

  get 'producto_biology_finals', to: 'biology_finals#indexProducts'
  get 'producto_biology_finals/:id', to: 'biology_finals#showProduct'

  #BIOCHEMISTRY
  get 'producto_biochemistries', to: 'biochemistries#indexProducts'
  get 'producto_biochemistries/:id', to: 'biochemistries#showProduct'

  get 'producto_biochemistry_finals', to: 'biochemistry_finals#indexProducts'
  get 'producto_biochemistry_finals/:id', to: 'biochemistry_finals#showProduct'

  scope :admin do
    resources :users do
      collection do
        get 'generate_random_string'
      end
    end

    resources :extras do
      resources :extra_contents
    end

    resources :physiologies do
      resources :physiology_contents
    end
    resources :anatomy_as do
      resources :anatomy_a_contents
    end
    resources :anatomy_bs do
      resources :anatomy_b_contents
    end
    resources :anatomy_cs do
      resources :anatomy_c_contents
    end
    resources :histologies do
      resources :histology_contents
    end
    resources :biologies do
      resources :biology_contents
    end
    resources :biochemistries do
      resources :biochemistry_contents
    end

    resources :anatomy_a_finals do
      resources :anatomy_a_final_contents
    end

    resources :anatomy_b_finals do
      resources :anatomy_b_final_contents
    end

    resources :anatomy_c_finals do
      resources :anatomy_c_final_contents
    end

    resources :histology_finals do
      resources :histology_final_contents
    end

    resources :biology_finals do
      resources :biology_final_contents
    end

    resources :biochemistry_finals do
      resources :biochemistry_final_contents
    end

    resources :physiology_finals do
      resources :physiology_final_contents
    end
    # resources :finals, path: 'final' do
    #   resources :final_contents
    # end
  end
end

app/models/anatomy_a.rb
class AnatomyA < ApplicationRecord
  has_many :anatomy_a_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/anatomy_a_final.rb
class AnatomyAFinal < ApplicationRecord
  has_many :anatomy_a_final_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/anatomy_b.rb
class AnatomyB < ApplicationRecord
  has_many :anatomy_b_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/anatomy_b_final.rb
class AnatomyBFinal < ApplicationRecord
  has_many :anatomy_b_final_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/anatomy_c.rb
class AnatomyC < ApplicationRecord
  has_many :anatomy_c_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/anatomy_c_final.rb
class AnatomyCFinal < ApplicationRecord
  has_many :anatomy_c_final_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/biochemistry.rb
class Biochemistry < ApplicationRecord
  has_many :biochemistry_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/biology.rb
class Biology < ApplicationRecord
  has_many :biology_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/biology_content.rb
class BiologyContent < ApplicationRecord
  belongs_to :biology
end
  

app/models/biology_final.rb
class BiologyFinal < ApplicationRecord
  has_many :biology_final_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/extra.rb
class Extra < ApplicationRecord
  has_many :extra_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/extra_content.rb
class ExtraContent < ApplicationRecord
  belongs_to :extra
end
  

app/models/histology.rb
class Histology < ApplicationRecord
  has_many :histology_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/histology_final.rb
class HistologyFinal < ApplicationRecord
  has_many :histology_final_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/physiology.rb
class Physiology < ApplicationRecord
  has_many :physiology_contents, dependent: :destroy

  validates :title, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  
  validates :first_name, :last_name, presence: true, format: { with: /\A[a-zA-Z\ñÑ\u00C0-\u017F\']+[\s?[a-zA-Z\ñÑ\u00C0-\u017F\']*]*\z/ }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }, if: -> {  changes[:email] }

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }

  enum role: %i[administrador estudiante]

  validates :role, presence: true

  before_save :set_default_permissions, if: :administrador?

  private

  def set_default_permissions
    self.anatomia_a_cursada = true
    self.anatomia_a_final = true
    self.anatomia_b_cursada = true
    self.anatomia_b_final = true
    self.anatomia_c_cursada = true
    self.anatomia_c_final = true
    self.histologia_cursada = true
    self.histologia_final = true
    self.biologia_cursada = true
    self.biologia_final = true
    self.fisiologia_cursada = true
    self.fisiologia_final = true
    self.bioquimica_cursada = true
    self.bioquimica_final = true
  end
  
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="inner">
    <section style="width: 100%; margin-right: 0;">
      <h2 style="text-align: center;"><%= link_to 'Bottassi & Milone', root_path, class:"btn_as_link" %></h2>
      
      <ul class="divided icons col-12 col-12-mobile" style="text-align: center;">
        <li class="icon brands fa-instagram">
          <a href="https://www.instagram.com/instituto.bm?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" target="_blank" rel="noopener noreferrer">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/50px-Instagram_icon.png" alt="Instagram">
          </a>
        </li>
        <li class="icon brands fa-whatsapp">
          <a href="https://wa.link/airk2w" target="_blank" rel="noopener noreferrer">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/WhatsApp.svg/57px-WhatsApp.svg.png" alt="WhatsApp">
          </a>
        </li>
      </ul>

    </section>
    <ul class="copyright" style="text-align: center;">
      <li class="icon brands">
        <a href="https://portfolio-gp7q0fyut-bottassijuanignacio.vercel.app/" target="_blank">Programador Juan Ignacio Bottassi</a>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div id="sidebar-menu">
  <button id='nav-toggle' class="bi bi-list"></button>
  <nav class="nav-burger" id="nav-burger">
    
    <ul>
      <li class="current-user-name"><%= "#{current_user.first_name} #{current_user.last_name}" %></li>
      
      <% if current_user.role === "administrador" %>
        <li><%= link_to 'Panel de Administrador', users_path, class:"btn_as_link" %></li>
      <% end %>
      
      <li><%= link_to 'B&M', root_path, class:"btn_as_link" %></li>
    
      <% if current_user.anatomia_a_cursada %>
        <li><%= link_to 'Anatomía A Cursada', producto_anatomy_as_path, class:"btn_as_link" %></li>
      <% end %>

      <% if current_user.anatomia_a_final %>
        <li><%= link_to 'Anatomía A Final', producto_anatomy_a_finals_path, class:"btn_as_link" %></li>
      <% end %>
      
      <% if current_user.anatomia_b_cursada %>
        <li><%= link_to 'Anatomía B Cursada', producto_anatomy_bs_path, class:"btn_as_link" %></li>
      <% end %>

      <% if current_user.anatomia_b_final %>
        <li><%= link_to 'Anatomía B Final', producto_anatomy_b_finals_path, class:"btn_as_link" %></li>
      <% end %>

      <% if current_user.anatomia_c_cursada %>
        <li><%= link_to 'Anatomía C Cursada', producto_anatomy_cs_path, class:"btn_as_link" %></li>
      <% end %>

      <% if current_user.anatomia_c_final %>
        <li><%= link_to 'Anatomía C Final', producto_anatomy_c_finals_path, class:"btn_as_link" %></li>
      <% end %>
      
      <% if current_user.fisiologia_cursada %>
        <li><%= link_to 'Fisiología Cursada', producto_physiologies_path, class:"btn_as_link" %></li>
      <% end %>

      <% if current_user.fisiologia_final %>
        <li><%= link_to 'Fisiología Final', producto_physiology_finals_path, class:"btn_as_link" %></li>
      <% end %>

      <% if current_user.biologia_cursada %>  
        <li><%= link_to 'Biología Cursada', producto_biologies_path, class:"btn_as_link" %></li>
      <% end %>

      <% if current_user.biologia_final %>  
        <li><%= link_to 'Biología Final', producto_biology_finals_path, class:"btn_as_link" %></li>
      <% end %>
      
      <% if current_user.histologia_cursada %>
        <li><%= link_to 'Histología Cursada', producto_histologies_path, class:"btn_as_link" %></li>
      <% end %>

      <% if current_user.histologia_final %>
        <li><%= link_to 'Histología Final', producto_histology_finals_path, class:"btn_as_link" %></li>
      <% end %>
      
      <% if current_user.bioquimica_cursada %>
        <li><%= link_to 'Bioquímica Cursada', producto_biochemistries_path, class:"btn_as_link" %></li>
      <% end %>

      <% if current_user.bioquimica_final %>
        <li><%= link_to 'Bioquímica Final', producto_biochemistry_finals_path, class:"btn_as_link" %></li>
      <% end %>
        
      <li><%= link_to 'Nosotros', about_path, class:"btn_as_link" %></li>
      <li><%= link_to 'Extra', producto_extras_path, class:"btn_as_link" %></li>

      <% if logged_in? %>
        <li><%= button_to 'Cerrar Sesión', logout_path, method: :post, class:"navbar-logout" %></li>
      <% end %>
    </ul>
  </nav>
</div>
<style>
  #sidebar-menu {
    background-color: #ede8df;
  }
  
  #nav-burger {
    display: none;
    transition: transform 1.5s ease-in-out;
    z-index: 100;
    background-color: rgb(54, 54, 54);
    position: fixed;
    width: 25%;
    height: 100%;
    color: white !important;
    overflow-y: auto;
  }
  
  #nav-burger::after {
    content: '';
    position: fixed;
    top: 0;
    left: 25%;
    width: 75%;
    height: 100%;
    background-color: white;
    opacity: 0.7;
    z-index: 99;
  }
  #nav-burger h2{
    padding: 10px;
    margin: 5px;
  }
  
  #nav-burger.show-nav {
    display: block;
  }
  
  #nav-burger a {
    color: whitesmoke;
    
  }
  
  #nav-burger ul {
    list-style-type: none;
    font-size: 0.8rem;
  }
  
  #nav-burger .navbar-logout{
    background-color: white;
    padding: 0;
    width: 50%;
    font-size: 10px;
  }
  
  #nav-burger li {
    margin: 5px;
  }
  @media (max-width: 375px) {
      #nav-burger {
        width: 62%;
      }

      #nav-burger::after{
        left: 62%;
      }

      #nav-burger .navbar-logout{
        width: 75%;
        font-size: 0.5rem;
      }
  }
  @media (max-width: 430px) {
      #nav-burger {
        width: 50%;
      }

      #nav-burger::after{
        left: 50%;
        width: 50%;
      }

      #nav-burger .navbar-logout{
        width: 75%;
        color: black;
        font-size: 0.5rem;
      }

      #nav-burger ul {
        font-size: 12px;
      }
  }
</style>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.addEventListener('click', function (event) {
      const menuToggle = document.getElementById('nav-toggle');
      const menu = document.getElementById('nav-burger');

      if (event.target === menuToggle) {
        menu.classList.toggle('show-nav');
        if (menu.classList.contains('show-nav')) {
          menuToggle.classList.remove('bi-list');
          menuToggle.classList.add('bi-x-lg');
        } else {
          menuToggle.classList.remove('bi-x-lg');
          menuToggle.classList.add('bi-list');
        }
      } else if (menu.classList.contains('show-nav') && menu.contains(event.target)) {
        menu.classList.remove('show-nav');
        menuToggle.classList.remove('bi-x-lg');
        menuToggle.classList.add('bi-list');
      }
      
    });
  });
</script>

app/views/shared/_navbar_admin.html.erb
<div id="admin-menu">
  <button id='admin-toggle' class="bi bi-arrow-left-square-fill"></button>
  <nav class="admin-nav" id="admin-nav">
    <ul>
      <li><%= link_to "Nuevo Usuario", new_user_path %></li>

      <li><%= link_to "Anatomía A Cursada", anatomy_as_path %></li>

      <li><%= link_to "Anatomía A Final", anatomy_a_finals_path %></li>

      <li><%= link_to "Anatomía B Cursada", anatomy_bs_path %></li>

      <li><%= link_to "Anatomía B Final", anatomy_b_finals_path %></li>
    
      <li><%= link_to "Anatomía C Cursada", anatomy_cs_path %></li>

      <li><%= link_to "Anatomía C Final", anatomy_c_finals_path %></li>

      <li><%= link_to "Biología Cursada", biologies_path %></li>

      <li><%= link_to "Biología Final", biology_finals_path %></li>
      
      <li><%= link_to "Bioquímica Cursada", biochemistries_path %></li>

      <li><%= link_to "Bioquímica Final", biochemistry_finals_path %></li>

      <li><%= link_to "Histología Cursada", histologies_path %></li>

      <li><%= link_to "Histología Final", histology_finals_path %></li>

      <li><%= link_to "Fisiología Cursada", physiologies_path %></li>

      <li><%= link_to "Fisiología Final", physiology_finals_path %></li>

      <li><%= link_to "Extras", extras_path %></li>
    </ul>
  </nav>
</div>
<style>
  #admin-nav {
    display: none;
    transition: transform 1.5s ease-in-out;
    z-index: 100;
    background-color: rgb(54, 54, 54);
    position: fixed;
    width: 25%;
    height: 100%;
    color: white !important;
    overflow-y: auto;
  }
  
  #admin-nav::after {
    content: '';
    position: fixed;
    top: 0;
    left: 0%;
    width: 75%;
    height: 100%;
    background-color: white;
    opacity: 0.7;
    z-index: 99;
  }
  #admin-nav h2{
    padding: 10px;
    margin: 5px;
  }
  
  #admin-nav.show-nav {
    display: block;
  }
  
  #admin-nav a {
    color: whitesmoke;
    
  }
  
  #admin-nav ul {
    list-style-type: none;
  }
  
  #admin-nav .navbar-logout{
    background-color: white;
    padding: 0;
    width: 100%;
    font-size: 10px;
  }
  
  #admin-nav li {
    margin: 5px;
  }

  #admin-toggle {
    padding: 7px 10px 10px 10px;
    position: absolute;
    right: 0;
    top: 0;
  }

  @media (max-width: 375px) {
      #admin-nav {
        width: 62%;
        position: absolute;
        right: 0;
      }

      #admin-nav::after{
        left: 0%;
      }

      #admin-nav .navbar-logout{
        width: 75%;
      }
  }
  @media (max-width: 430px) {
      #admin-nav {
        width: 50%;
        right: 0;
      }

      #admin-nav::after{
        left: 0%;
        width: 50%;
      }

      #admin-nav .navbar-logout{
        width: 75%;
        color: black;
      }

      #admin-nav ul {
        font-size: 12px;
      }
  }
  @media (min-width: 430px) {
    #admin-nav {
      width: 50%;
      right: 0;
    }

    #admin-nav::after{
      left: 0%;
      width: 50%;
    }
  }
  @media (min-width: 1024px) {
    #admin-nav {
      width: 25%;
      right: 0;
    }

    #admin-nav::after{
      left: 0%;
      width: 75%;
    }
  }
</style>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.addEventListener('click', function (event) {
      const menuToggle = document.getElementById('admin-toggle');
      const menu = document.getElementById('admin-nav');

      if (event.target === menuToggle) {
        menu.classList.toggle('show-nav');
        if (menu.classList.contains('show-nav')) {
          menuToggle.classList.remove('bi-arrow-left-square-fill');
          menuToggle.classList.add('bi-arrow-right-square-fill');
          } else {
            menuToggle.classList.remove('bi-arrow-right-square-fill');
            menuToggle.classList.add('bi-arrow-left-square-fill');
        }
      } else if (menu.classList.contains('show-nav') && menu.contains(event.target)) {
        menu.classList.remove('show-nav');
        menuToggle.classList.remove('bi-arrow-right-square-fill');
        menuToggle.classList.add('bi-arrow-left-square-fill');
      }
      
    });
  });
</script>